pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    sh "docker build -f 02-first-pipeline/Dockerfile -t darkmtrance/homer_page:1.0.0-${BUILD_ID} 02-first-pipeline"
                }
            }
        }
        stage('docker push') {
            steps {
                script {
                    sh "docker push darkmtrance/homer_page:1.0.0-${BUILD_ID}"
                }
            }
        }
    }
}